#!/bin/sh
# Update UFO after any edits other than with FontForge and prior to commit

# Stop on any errors
set -e

# Check and normalize all UFOs first -- assumes no other steps de-normalize
echo "Normalizing UFOs..."
psfnormalize -p checkfix=fix source/masters/*-Regular.ufo  &
psfnormalize -p checkfix=fix source/masters/*-Bold.ufo  &
wait

echo "Updating glyph orders in Regular..."
psfsetglyphorder -q -p checkfix=none -p backup=False --header DesignerOrder,DesignerOrder --field public.glyphOrder,com.schriftgestaltung.glyphOrder -i source/glyph_data.csv source/masters/*-Regular.ufo

echo "Updating production names in Regular..."
psfsetpsnames -q -p checkfix=none -p backup=False -i source/glyph_data.csv source/masters/*-Regular.ufo
psfsetpsnames -q -p checkfix=none -p backup=False -i source/glyph_data.csv source/masters/*-Bold.ufo

echo "Syncing glyph orders, psnames, and other metadata to other UFOs..."
psfsyncmasters -p scrlevel=w --complex source/Ruwudu.designspace

echo "Updating woff metadata files..."
psfmakewoffmetadata -q -n ruwudu      -i org.sil.fonts -o source/Ruwudu-WOFF-metadata.xml source/masters/*-Regular.ufo  

echo "Building internal fea..."
psfmakefea -q -o source/masters/Ruwudu-Regular.ufo/features.fea -l Ruwudu-Regular-psfmakefea.log -i source/opentype/master.feax --omitaps "topright, ogonek, caret_1, caret_2, caret_3, top_3, top_4, top_alef" source/masters/*-Regular.ufo &
psfmakefea -q -o source/masters/Ruwudu-Bold.ufo/features.fea -l Ruwudu-Bold-psfmakefea.log -i source/opentype/master.feax --omitaps "topright, ogonek, caret_1, caret_2, caret_3, top_3, top_4, top_alef" source/masters/*-Bold.ufo &

wait

echo "preflight completed!"
